### ISSUE TITLE
id's vs classes

### ISSUE THREAD

**Issue by rimmesbe** [beckandre/prj-rev-bwfs-dasmoto#3]
Id's are meant to be unique identifiers, meaning that each id can only be used one time per html page. What you want to use here is class="price" as classes can be shared amongst many elements.

https://github.com/beckandre/prj-rev-bwfs-dasmoto/blob/master/ArtsCrafts/index.html#L20

**Comment by beckandre** [comment]
Thank you - did not realize id can only be used one time per html page.
