### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [beckandre/prj-rev-bwfs-dasmoto#6]
Grade: Needs improvement

Summary: You have a good start to this project, and had some correct instincts. Take a look at the issues I created and see if you can implement fixes. It is going to be important to structure html correctly for organization and for page layouts on larger projects in the future. Here is a good article with examples: http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by beckandre** [comment]
Thanks for your helpful comments! And I appreciate Shay Howe's article and examples.
I improved the code organization and cleaned up the CSS, but was unsuccessful after more hours of trying to add the background image behind the h1 text. Last resort: I copied Codecademy's code from Chrome's dev tool, but that didn't work either. There are many ways to accomplish this, no doubt, but I would really appreciate your help. Happy holidays!
